# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Newton-Raphson algorithm for cauchy(theta) using Rcpp.
#' @description Using three input to get the result of Newton-Raphson algorithm of cauchy distribution.
#' @param x the data of cauchy distribution
#' @param theta the initial value
#' @param method method=1 for one step iteration and method=2 for multi-step iteration
#' @return the estimation of param theta
#' @examples
#' \dontrun{
#' x<-rcauchy(200,location=1)
#' theta<-median(x)
#' thetahat<-NC(x,theta,1)
#' print(thetahat)
#' }
#' @export
NC <- function(x, theta, method) {
    .Call('_SA24204136_NC', PACKAGE = 'SA24204136', x, theta, method)
}

#' @title Fisher scoring algorithm for cauchy(theta) using Rcpp.
#' @description Using three input to get the result of Fisher scoring algorithm of cauchy distribution.
#' @param x the data of cauchy distribution
#' @param theta the initial value
#' @param method method=1 for one step iteration and method=2 for multi-step iteration
#' @return the estimation of param theta
#' @examples
#' \dontrun{
#' x<-rcauchy(200,location=1)
#' theta<-median(x)
#' thetahat<-FSC(x,theta,1)
#' print(thetahat)
#' }
#' @export
FSC <- function(x, theta, method) {
    .Call('_SA24204136_FSC', PACKAGE = 'SA24204136', x, theta, method)
}

